### ISSUE TITLE
html(5) validation

### ISSUE THREAD

**Issue by gockelhahn** [ciex/metawahl#2]
when checking this site (lets say: https://metawahl.de/tags/ladenoffnungszeit) with the w3c html validator (https://validator.w3.org/#validate_by_input), we gather some errors and warnings you might want to fix:

errors:
> - Element div not allowed as child of element h1 in this context.
> - Element p not allowed as child of element h2 in this context.
> - Element div not allowed as child of element h2 in this context.
> - Attribute value not allowed on element a at this point.
> - Bad value listitem for attribute role on element a.

warnings:
> - This document appears to be written in German but the html start tag has lang="en". Consider using lang="de" (or variant) instead.
> - The button role is unnecessary for element button.
> - The type attribute is unnecessary for JavaScript resources.

further pages have not been checked, so other errors can probably pop up

**Comment by ciex** [comment]
Thanks Felix. It's not officially launched right now. After Feb 28th I will
look into this.

Am 10.02.2018 11:55 vorm. schrieb "Felix Bolte" <notifications@github.com>:

when checking this site (lets say: https://metawahl.de/tags/
ladenoffnungszeit) with the w3c html validator (https://validator.w3.org/#
validate_by_input), we gather some errors and warnings you might want to
fix:

errors:


   - Element div not allowed as child of element h1 in this context.
   - Element p not allowed as child of element h2 in this context.
   - Element div not allowed as child of element h2 in this context.
   - Attribute value not allowed on element a at this point.
   - Bad value listitem for attribute role on element a.

warnings:


   - This document appears to be written in German but the html start tag
   has lang="en". Consider using lang="de" (or variant) instead.
   - The button role is unnecessary for element button.
   - The type attribute is unnecessary for JavaScript resources.

further pages have not been checked, so other errors can probably pop up

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ciex/metawahl/issues/2>, or mute the thread

**Comment by ciex** [comment]
Danke für den Hinweis Felix. Die Validierung gibt noch Fehler, weil ich gerade oft Sachen ändere. Für den offiziellen Launch am 28.Februar werde ich das noch fixen. Vielleicht lässt sich ja auch Travis so einrichten, dass das mitgeprüft wird.

**Comment by ciex** [comment]
https://validator.w3.org/unicorn/check?ucn_uri=https%3A%2F%2Fmetawahl.de%2Fthemen%2Fladenoffnungszeit%2F&ucn_task=conformance#
